# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: Michael J. Miller
email: michael.joseph.miller@gmail.com
description: >- # Ignore newlines until "baseurl:"
  Portfolio showcasing IT and programming skills
baseurl: '' # Empty for root deployment on GitHub Pages
url: 'https://mjmiller41.github.io' # Your GitHub Pages URL
github_username: mjmiller41

# Navigation
header_pages:
  - index.md
  - _pages/about.md
  - _pages/skills.md
  - _pages/projects.md
  - _pages/education.md
  - _pages/contact.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Include files/folders
include:
  - _pages

defaults:
  - scope:
      path: 'assets/images'
    values:
      image: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
